## Description of the project

This dataset contains statistics on the world's billionaires, including information about their businesses, industries, and personal details. It provides insights into the wealth distriution, business sectors, and demographics of billionaires worldwide.

(**This is the Kaggle description. It can be changed to provide a more meaningful and complete description once I dive deeper into the data**)

#### Data dictionary:

1. rank: The ranking of the billionaire in terms of wealth.
2. finalWorth: The final net work of the billionaire in USD.
3. category: The category or industry in which the billionaire's business operates.
4. personName: The full name of the billionaire.
5. age: The age of the billionaire.
6. country: The country in which the billionaire resides.
7. city: The city in which the billionaire resides.
8. source: The source of the billionaire's wealth.
9. industries: The industries associated with the billionaire's business interests.
10. countryOfCitizenship: The country of citizenship of the billionaire.
11. organization: The name of the organization or company associated with the billionaire.
12. selfMade: Indicates whether the billionaire is self-made (True/False).
13. status: "D' represents self-made billionaires (Founders/Entrepreneurs) and "U" indicates inherited or unerarned wealth.
14. gender: The gender of the billionaire.
15. birthDate: The birthdate of the billionaire.
16. lastName: The last name of the billionaire.
17. firstName: The first name of the billionaire.
18. title: The title or honorifitc of the billionaire.
19. date: The data of data collection.
20. state: The state in which the billionaire resides.
21. residenceStateRegion. The region or state of residence of the billionaire.
22. birthYear: The birth year of the billionaire.
23. birthMonth: The birth month of the billionaire.
24. birthDate: The birth day of the billionaire.
25. cpi_country: Consumer Price Index (CPI) for the billionaire's country.
26. cpi_change_country: CPI change for the billionaire's country.
27. gdp_country: Gross Domestic Product (GDP) for the billionaire's country.
28. gross_tertiary_education_enrollment: Enrollment in tertiary education in the billionaire's country.
29. gross_primary_education_enrollment_country: Enrollment in primary education in the billionaire's country.
30. life_expectancy_country: Life's expectancy in the billionaire's country.
31. tax_revenue_country_country: Tax revenue in the billionaire's country.
32. total_tax_rate_country: Total tax rate in the billionaire's country.
33. population_country: Population of the billionaire's country.
34. latitude_country: Latitude coordinate of the billionaire's country.
35. longitude_country: Longitude coordinate of the billionaire's country.

#### Importing libraries, changing settings to display all columns and loading the dataset

### Part 1. Setting up the environment for the project

In [343]:
# We're going to use the following libraries in this project.

import pandas as pd
import numpy as np

In [344]:
# Set option to display all columns when viewing the dataset.

pd.set_option('display.max_columns', None)

In [345]:
# Loading the dataset

df_billions = pd.read_csv('Billionaires Statistics Dataset.csv', encoding='utf-8')


#### First look at the dataset

In [346]:
# Summarize the dataset size and structure

print(f'The dataset contains {df_billions.shape[0]:,} rows and {df_billions.shape[1]:,} columns')
print(f'The total number of values contained in the dataset is {df_billions.size:,}')

The dataset contains 2,640 rows and 35 columns
The total number of values contained in the dataset is 92,400


In [347]:
# Using the head() function to take a first look to the dataset

df_billions.head(10)

rank  finalWorth               category                 personName   age  \
0     1      211000       Fashion & Retail   Bernard Arnault & family  74.0   
1     2      180000             Automotive                  Elon Musk  51.0   
2     3      114000             Technology                 Jeff Bezos  59.0   
3     4      107000             Technology              Larry Ellison  78.0   
4     5      106000  Finance & Investments             Warren Buffett  92.0   
5     6      104000             Technology                 Bill Gates  67.0   
6     7       94500  Media & Entertainment          Michael Bloomberg  81.0   
7     8       93000                Telecom  Carlos Slim Helu & family  83.0   
8     9       83400            Diversified              Mukesh Ambani  65.0   
9    10       80700             Technology              Steve Ballmer  67.0   

         country         city              source             industries  \
0         France        Paris                LVMH       Fashion & Retail   
1  United States       Austin       Tesla, SpaceX             Automotive   
2  United States       Medina              Amazon             Technology   
3  United States        Lanai              Oracle             Technology   
4  United States        Omaha  Berkshire Hathaway  Finance & Investments   
5  United States       Medina           Microsoft             Technology   
6  United States     New York        Bloomberg LP  Media & Entertainment   
7         Mexico  Mexico City             Telecom                Telecom   
8          India       Mumbai         Diversified            Diversified   
9  United States  Hunts Point           Microsoft             Technology   

  countryOfCitizenship                      organization  selfMade status  \
0               France  LVMH Moët Hennessy Louis Vuitton     False      U   
1        United States                             Tesla      True      D   
2        United States                            Amazon      True      D   
3        United States                            Oracle      True      U   
4        United States    Berkshire Hathaway Inc. (Cl A)      True      D   
5        United States   Bill & Melinda Gates Foundation      True      D   
6        United States                         Bloomberg      True      U   
7               Mexico                     América Móvil      True      U   
8                India               Reliance Industries     False      D   
9        United States              Los Angeles Clippers      True      D   

  gender        birthDate   lastName firstName                 title  \
0      M    3/5/1949 0:00    Arnault   Bernard      Chairman and CEO   
1      M   6/28/1971 0:00       Musk      Elon                   CEO   
2      M   1/12/1964 0:00      Bezos      Jeff  Chairman and Founder   
3      M   8/17/1944 0:00    Ellison     Larry       CTO and Founder   
4      M   8/30/1930 0:00    Buffett    Warren                   CEO   
5      M  10/28/1955 0:00      Gates      Bill               Cochair   
6      M   2/14/1942 0:00  Bloomberg   Michael                   CEO   
7      M   1/28/1940 0:00  Slim Helu    Carlos     Honorary Chairman   
8      M   4/19/1957 0:00     Ambani    Mukesh  Founder and Chairman   
9      M   3/24/1956 0:00    Ballmer     Steve                 Owner   

            date       state residenceStateRegion  birthYear  birthMonth  \
0  4/4/2023 5:01         NaN                  NaN     1949.0         3.0   
1  4/4/2023 5:01       Texas                South     1971.0         6.0   
2  4/4/2023 5:01  Washington                 West     1964.0         1.0   
3  4/4/2023 5:01      Hawaii                 West     1944.0         8.0   
4  4/4/2023 5:01    Nebraska              Midwest     1930.0         8.0   
5  4/4/2023 5:01  Washington                 West     1955.0        10.0   
6  4/4/2023 5:01    New York            Northeast     1942.0         2.0   
7  4/4/2023 5:01         NaN                  N

After using the ```head()```, we can extract the following conclusions:
1. Column names display a mix of CamelCase, lowercase and underscore this can be standardize for the sake of uniformity.

2. At first glance, some columns with numeric values are floats (e.g., age, birthYear). Integers are a better choice here because, in general, these types of data don't use decimals.

3. Columns *state* and *residenceStateRegion* seem to contain data only when the *countryOfCitizenship* column is equal to 'United States'. Both columns could be useful for some deeper analysis into the subset data belonging to this country, but if this assumption is correct, for the overall EDA, they have little value.

In [348]:
# Displaying a few random samples from the dataset to investigate further

df_billions.sample(10, random_state=42)

rank  finalWorth               category                   personName  \
2005  1905        1500     Gambling & Casinos                Jens von Bahr   
32      33       38000            Diversified                  Li Ka-shing   
962    949        3100       Fashion & Retail                 Aerin Lauder   
1461  1434        2100            Diversified                  Douglas Hsu   
478    466        5500  Media & Entertainment             Katharine Rayner   
1272  1272        2400             Automotive  Abdulla Al Futtaim & family   
211    208        9200             Technology                  Azim Premji   
1309  1272        2400          Manufacturing        Yang Weidong & family   
1745  1725        1700            Real Estate             William Heinecke   
1498  1434        2100        Food & Beverage        Sun Mengquan & family   

       age               country          city                     source  \
2005  52.0                Sweden     Stockholm          Gambling products   
32    94.0             Hong Kong           NaN                Diversified   
962   52.0         United States      New York               Estee Lauder   
1461  80.0                Taiwan        Taipei                Diversified   
478   78.0         United States  East Hampton          Media, automotive   
1272  83.0  United Arab Emirates         Dubai  Auto dealers, investments   
211   77.0                 India     Bangalore          Software services   
1309  54.0                 China       Jiaxing                  Chemicals   
1745  73.0              Thailand       Bangkok                     Hotels   
1498  73.0                 China        Yantai                 Edible oil   

                 industries  countryOfCitizenship           organization  \
2005     Gambling & Casinos                Sweden                    NaN   
32              Diversified             Hong Kong  CK Hutchison Holdings   
962        Fashion & Retail         United States                    NaN   
1461            Diversified                Taiwan                    NaN   
478   Media & Entertainment         United States                    NaN   
1272             Automotive  United Arab Emirates                    NaN   
211              Technology                 India             Wipro Ltd.   
1309          Manufacturing                 China                    NaN   
1745            Real Estate              Thailand                    NaN   
1498        Food & Beverage                 China                    NaN   

      selfMade status gender       birthDate    lastName  firstName  \
2005      True      U      M  2/22/1971 0:00    von Bahr       Jens   
32        True      U      M  6/13/1928 0:00          Li   Ka-shing   
962      False      D      F  4/23/1970 0:00      Lauder      Aerin   
1461     False      D      M  8/24/1942 0:00         Hsu    Douglas   
478      False      U      F  1/12/1945 0:00      Rayner  Katharine   
1272     False      D      M   1/1/1940 0:00  Al Futtaim    Abdulla   
211      False      D      M  7/24/1945 0:00      Premji       Azim   
1309      True      D      M   9/9/1968 0:00        Yang    Weidong   
1745      True      E      M   6/4/1949 0:00    Heinecke    William   
1498      True      D      M   3/1/1950 0:00         Sun   Mengquan   

                 title           date     state residenceStateRegion  \
2005               NaN  4/4/2023 5:01       NaN                  NaN   
32      Senior Advisor  4/4/2023 5:01       NaN                  NaN   
962                NaN  4/4/2023 5:01  New York            Northeast   
1461               NaN  4/4/2023 5:01       NaN                  NaN   
478                NaN  4/4/2023 5:01  New York            Northeast   
1272               NaN  4/4/2023 5:01       NaN                  NaN   
211   Founder Chairman  4/4/2023 5:01       NaN                  NaN   
1309               NaN  4/4/2023 5:01       NaN                  NaN   
1745               NaN  4/4/2023

The ```sample()``` function provides additional information:
1. There are null values presented in the dataset, in particular where the *country* column is a disputed territory (e.g., Taiwan) or a subdivision (e.g., Hong Kong). Also, the *organization* column seems to have many null values as well.

2. *status* and *gender* columns are abbreviated. Without a data dictionary, it may be difficult for anyone not familiarized with the dataset to guess what these columns mean when looking at the data directly. These values could be converted into a meaningful strings and then transformed further for advanced processing or data modeling.

3. The *population_country* column is displayed with values in scientific notation, making it difficult to interpret them.

4. The previous assumption regarding the *state* and *residenceStateRegion* seems stronger, as the sample data confirms that for countries other than the United States, the values in this column are null.

#### Data types and summary statistics with ``dtypes``, ``info()`` and ``describe()``

In [349]:
# Using dtypes to check what type of data is contained in each column

df_billions.dtypes

rank                                            int64
finalWorth                                      int64
category                                       object
personName                                     object
age                                           float64
country                                        object
city                                           object
source                                         object
industries                                     object
countryOfCitizenship                           object
organization                                   object
selfMade                                         bool
status                                         object
gender                                         object
birthDate                                      object
lastName                                       object
firstName                                      object
title                                          object
date                        

In [350]:
# Displaying the count of each data type in the dataset

dtype_counts = df_billions.dtypes.value_counts()

# Loop through the unique data tpyes and print sentences

for dtype, count in dtype_counts.items():
    print(f'There are {count} columns with data type {dtype} in the dataset')

There are 18 columns with data type object in the dataset
There are 14 columns with data type float64 in the dataset
There are 2 columns with data type int64 in the dataset
There are 1 columns with data type bool in the dataset


After using the `dtypes` attribute, the following can be said:
1. Objects (aka strings) are the most common data type in the dataset. However, some of them like *birthDate* and *date* should be converted into the appropriate data type, just to name a few.

2. The dataset has two columns that apparently give the same information in a different way:

   1. The *selfMade* column tells us whether the billionaire is self-made. It's a boolean data type.
   2. The *status* column represents a self-made billionaires with a 'D' and billionaires with inherited or unearned wealth with an 'U'.

   These two columns should match, it wouldn't have sense a row with a `True` value in the *selfMade* column and an 'U' value in the *status* column, indicating the billionaire's wealth as inherited or unearned. More info about this in the data quality section.

3. The *gdp_country* column has an `object` data type because of the $ symbol before the value of the country's GDP. It should be converted into the appropriate type to use it in the EDA.

In [351]:
# Using the info method to get a summary of the dataset

df_billions.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2640 entries, 0 to 2639
Data columns (total 35 columns):
 #   Column                                      Non-Null Count  Dtype  
---  ------                                      --------------  -----  
 0   rank                                        2640 non-null   int64  
 1   finalWorth                                  2640 non-null   int64  
 2   category                                    2640 non-null   object 
 3   personName                                  2640 non-null   object 
 4   age                                         2575 non-null   float64
 5   country                                     2602 non-null   object 
 6   city                                        2568 non-null   object 
 7   source                                      2640 non-null   object 
 8   industries                                  2640 non-null   object 
 9   countryOfCitizenship                        2640 non-null   object 
 10  organization

In [352]:
df_billions.describe()

rank     finalWorth          age    birthYear   birthMonth  \
count  2640.000000    2640.000000  2575.000000  2564.000000  2564.000000   
mean   1289.159091    4623.787879    65.140194  1957.183307     5.740250   
std     739.693726    9834.240939    13.258098    13.282516     3.710085   
min       1.000000    1000.000000    18.000000  1921.000000     1.000000   
25%     659.000000    1500.000000    56.000000  1948.000000     2.000000   
50%    1312.000000    2300.000000    65.000000  1957.000000     6.000000   
75%    1905.000000    4200.000000    75.000000  1966.000000     9.000000   
max    2540.000000  211000.000000   101.000000  2004.000000    12.000000   

          birthDay  cpi_country  cpi_change_country  \
count  2564.000000  2456.000000         2456.000000   
mean     12.099844   127.755204            4.364169   
std       9.918876    26.452951            3.623763   
min       1.000000    99.550000           -1.900000   
25%       1.000000   117.240000            1.700000   
50%      11.000000   117.240000            2.900000   
75%      21.000000   125.080000            7.500000   
max      31.000000   288.570000           53.500000   

       gross_tertiary_education_enrollment  \
count                          2458.000000   
mean                             67.225671   
std                              21.343426   
min                               4.000000   
25%                              50.600000   
50%                              65.600000   
75%                              88.200000   
max                             136.600000   

       gross_primary_education_enrollment_country  life_expectancy_country  \
count                                 2459.000000              2458.000000   
mean                                   102.858520                78.122823   
std                                      4.710977                 3.730099   
min                                     84.700000                54.300000   
25%                                    100.200000                77.000000   
50%                                    101.800000                78.500000   
75%                                    102.600000                80.900000   
max                                    142.100000                84.200000   

       tax_revenue_country_country  total_tax_rate_country  \
count                  2457.000000             2458.000000   
mean                     12.546235               43.963344   
std                       5.368625               12.145296   
min                       0.100000                9.900000   
25%                       9.600000               36.600000   
50%                       9.600000               41.200000   
75%                      12.800000               59.100000   
max                      37.200000              106.300000   

       population_country  latitude_country  longitude_country  
count        2.476000e+03       2476.000000        2476.000000  
mean         5.102053e+08         34.903592          12.583156  
std          5.542447e+08         17.003497          86.762989  
min          3.801900e+04        -40.900557        -106.346771  
25%          6.683440e+07         35.861660         -95.712891  
50%          3.282395e+08         37.090240          10.451526  
75%          1.366418e+09         40.463667         104.195397  
max          1.397715e+09         61.924110         174.885971

From the `describe()` method, some insights can be made:
1. The dataset has 2,640 values, but the *rank* column maximum is 2,540. This suggests that some of the billionaire's included in the dataset have the same fortune, and thus, the same rank. Otherwise, the maximum value of the *rank* column should be equal to the number of rows in the dataset.

2. The minimum value in the *finalworth* column is 1,000. This means that a billionaire needs to have at least a fortune of 1 billion to be included. It's a way to validate our data is correct and only have billionaire and not millionaire people.

3. The maximum value of the *gross_tertiary_education_enrollment* and *gross_primary_education_enrollment* columns in greater than 100. It could be useful to dive deeper into the way these rates are calculated and if values greater than 100 make sense.

4. A similar thing can be said about the *tax_revenue_country_country* and *total_tax_rate_country* columns (in particular the last one, because it has a maximum value of 106).

#### Null values

##### First section. Figuring out null values

##### TL;DR

+ The dataset has 35 columns. Of them, 12 don't have any null value. 4 of them have more than 50% of null values and the rest are in between.

+ Null values are concentrated in specific columns. The four columns with highest null value proportion increase the occurrence of null values for the entire dataset. If these columns are removed, the same analysis shows a fall in the presence of null values from ~12% to less than 3%, with the highest proportion of null values being ~7%.

+ 

In [353]:
# Discovering the number of null values by column

df_billions.isna().sum()

rank                                             0
finalWorth                                       0
category                                         0
personName                                       0
age                                             65
country                                         38
city                                            72
source                                           0
industries                                       0
countryOfCitizenship                             0
organization                                  2315
selfMade                                         0
status                                           0
gender                                           0
birthDate                                       76
lastName                                         0
firstName                                        3
title                                         2301
date                                             0
state                          

In [354]:
# Calculate and format the percentage of null values for each column

na_percent = (df_billions.isnull().sum() / df_billions.shape[0] * 100).round(2)
na_percent

rank                                           0.00
finalWorth                                     0.00
category                                       0.00
personName                                     0.00
age                                            2.46
country                                        1.44
city                                           2.73
source                                         0.00
industries                                     0.00
countryOfCitizenship                           0.00
organization                                  87.69
selfMade                                       0.00
status                                         0.00
gender                                         0.00
birthDate                                      2.88
lastName                                       0.00
firstName                                      0.11
title                                         87.16
date                                           0.00
state       

In [355]:
# Categorizing columns based on the percentage of null values over the total rows presented in the dataset

# Initialize counts for each threshold range

count_0 = 0
count_0_25 = 0
count_25_50 = 0
count_50_75 = 0
count_75_100 = 0

# Iterate through the columns and accumulate counts within each threshold range

for percent in na_percent:
    if percent == 0:
        count_0 += 1
    elif percent > 0 and percent <= 25:
        count_0_25 += 1
    elif percent > 25 and percent <= 50:
        count_25_50 += 1
    elif percent > 50 and percent <= 75:
        count_50_75 += 1
    else:
        count_75_100 += 1

# Calculate the proportion for each threshold range

p_0 = count_0 / df_billions.shape[1]
p_0_25 = count_0_25 / df_billions.shape[1]
p_25_50 = count_25_50 / df_billions.shape[1]
p_50_75 = count_50_75 / df_billions.shape[1]
p_75_100 = count_75_100 / df_billions.shape[1]

# Create print statements to display results

print(f'{count_0} out of {df_billions.shape[1]} columns presented in the dataset ({p_0:.2%} of the total) have no null values')
print(f'{count_0_25} out of {df_billions.shape[1]} columns presented in the dataset ({p_0_25:.2%} of the total) have up to 25% null values')
print(f'{count_25_50} out of {df_billions.shape[1]} columns presented in the dataset ({p_25_50:.2%} of the total) have between 25% and 50% null values')
print(f'{count_50_75} out of {df_billions.shape[1]} columns presented in the dataset ({p_50_75:.2%} of the total) have between 50% and 75% of null values')
print(f'{count_75_100} out of {df_billions.shape[1]} columns presented in the dataset ({p_75_100:.2%} of the total) have more than 75% of null values')



12 out of 35 columns presented in the dataset (34.29% of the total) have no null values
19 out of 35 columns presented in the dataset (54.29% of the total) have up to 25% null values
0 out of 35 columns presented in the dataset (0.00% of the total) have between 25% and 50% null values
2 out of 35 columns presented in the dataset (5.71% of the total) have between 50% and 75% of null values
2 out of 35 columns presented in the dataset (5.71% of the total) have more than 75% of null values


Conducting a comparative analysis to discover the influence of columns with high proportion of null values

In [356]:
total_nulls = df_billions.isnull().sum().sum()
total_size = df_billions.size
null_p = total_nulls / total_size
median_null_p = np.median(df_billions.isnull().mean())

print(f'{total_nulls:,} out of {total_size:,} (or {null_p:.2%}) of the values are null')
print(f'The median null values per column  is {median_null_p:.2%}')

10,812 out of 92,400 (or 11.70%) of the values are null
The median null values per column  is 2.88%


In [357]:
na_percent.sort_values(ascending=False).head(5)

organization            87.69
title                   87.16
residenceStateRegion    71.70
state                   71.48
cpi_change_country       6.97
dtype: float64

In [358]:
# Slicing the dataset to drop columns with high proportion of null values

df_billions_subset = df_billions.drop(columns=['organization', 'title', 'residenceStateRegion', 'state'])
total_nulls_subset = df_billions_subset.isnull().sum().sum()
total_size_subset = df_billions_subset.size
null_p_subset = total_nulls_subset / total_size_subset
median_null_p_subset = np.median(df_billions_subset.isnull().mean())

print(f'{total_nulls_subset:,} out of {total_size_subset:,} (or {null_p_subset:.2%}) of the values are null')
print(f'The median null values per column is {median_null_p_subset:.2%}')

2,416 out of 81,840 (or 2.95%) of the values are null
The median null values per column is 2.73%


In [359]:
na_percent_subset = (df_billions_subset.isnull().sum() / df_billions.shape[0] * 100).round(2)

print(na_percent_subset.sort_values(ascending=False).head(5))
print("\n", na_percent_subset[na_percent_subset != 0].sort_values(ascending=False).tail(5))

cpi_country                            6.97
cpi_change_country                     6.97
tax_revenue_country_country            6.93
life_expectancy_country                6.89
gross_tertiary_education_enrollment    6.89
dtype: float64

 birthDate    2.88
city         2.73
age          2.46
country      1.44
firstName    0.11
dtype: float64


##### **Key takeaways from this subsection**

In this section, the following conclusions can be made:

1. 11.70% of the values in the dataset are nulls. This is the mean number of null values each column has. However, the median value of nulls in each column is 2.88%. This suggests that some columns have a high proportion of null values, thus increasing its overall presence in the dataset.

2. The columns with more null values are:
   1. *organization:* with a proportion of 87.69%.
   2. *title:* with a proportion of 87.16%.
   3. *residenceStateRegion:* with a proportion of 71.70%.
   4. *state:* with a proportion of 71.48%
   
   The last two columns are suspected to contain values only where the country column is equal to 'United States'. Further investigation is needed to verify this assumption.

3. When all these columns with high null value count are sliced from the dataset, the mean and median proportion of nulls falls to 2.95% and 2.73% in the order given.

4. After removing the 4 columns with high proportion of null values from the dataset, the highest number of null values can be found in the *cpi_country* and *cpi_change_country* columns.

5. The lowest amount of null values can be found in columns related millionaires' personal information, like *country* and firstName.

Dealing with null values

##### Figuring out the relation between the `country`, `state` and `residenceStateRegion`

In [360]:
# Making a copy of the original dataset to perform modifications

df_billions_na = df_billions.copy()

print((df_billions_na['country']!='United States').sum())
print(df_billions_na['state'].isna().sum())
print(df_billions_na['residenceStateRegion'].isna().sum())

1886
1887
1893


In [361]:
from IPython.display import display

# Creating filtered datasets to see null values in the selected columns

b_mask_1 = ((df_billions_na['state'].isna()) & (df_billions_na['country'] == 'United States'))
display(df_billions_na[b_mask_1])

b_mask_2 = ((df_billions_na['residenceStateRegion'].isna()) & (df_billions_na['country'] == 'United States'))
display(df_billions_na[b_mask_2])

rank  finalWorth         category                 personName   age  \
700   699        4000  Food & Beverage  Elisabeth DeLuca & family  75.0   

           country city  source       industries countryOfCitizenship  \
700  United States  NaN  Subway  Food & Beverage        United States   

    organization  selfMade status gender       birthDate lastName  firstName  \
700          NaN     False      N      F  7/25/1947 0:00   DeLuca  Elisabeth   

    title           date state residenceStateRegion  birthYear  birthMonth  \
700   NaN  4/4/2023 5:01   NaN                South     1947.0         7.0   

     birthDay  cpi_country  cpi_change_country           gdp_country  \
700      25.0       117.24                 7.5  $21,427,700,000,000    

     gross_tertiary_education_enrollment  \
700                                 88.2   

     gross_primary_education_enrollment_country  life_expectancy_country  \
700                                       101.8                     78.5   

     tax_revenue_country_country  total_tax_rate_country  population_country  \
700                          9.6                    36.6         328239523.0   

     latitude_country  longitude_country  
700          37.09024         -95.712891

rank  finalWorth               category       personName   age  \
358    352        6800             Technology     Gordon Moore  94.0   
521    511        5200            Real Estate         Sam Zell  81.0   
963    949        3100        Food & Beverage    Sheldon Lavin  90.0   
1339  1312        2300        Food & Beverage  Clayton Mathile  82.0   
1733  1725        1700        Food & Beverage    Carl DeSantis  83.0   
2167  2133        1300            Real Estate     Marvy Finger  87.0   
2547  2540        1000  Media & Entertainment    Jimmy Buffett  76.0   

            country           city                         source  \
358   United States       Woodside                          Intel   
521   United States        Chicago    Real estate, private equity   
963   United States  Highland Park                Meat processing   
1339  United States     Brookville                       Pet food   
1733  United States   Delray Beach                   Energy drink   
2167  United States        Houston                    Real estate   
2547  United States     Palm Beach  Entertainment, Margaritaville   

                 industries countryOfCitizenship organization  selfMade  \
358              Technology        United States  Intel Corp.      True   
521             Real Estate        United States          NaN      True   
963         Food & Beverage        United States          NaN      True   
1339        Food & Beverage        United States          NaN      True   
1733        Food & Beverage        United States          NaN      True   
2167            Real Estate        United States          NaN      True   
2547  Media & Entertainment        United States          NaN      True   

     status gender        birthDate  lastName firstName  \
358       D      M    1/3/1929 0:00     Moore    Gordon   
521       D      M   9/28/1941 0:00      Zell       Sam   
963       U      M   6/17/1932 0:00     Lavin   Sheldon   
1339      E      M   1/11/1941 0:00   Mathile   Clayton   
1733      U      M   7/19/1939 0:00  DeSantis      Carl   
2167      E      M   12/8/1935 0:00    Finger     Marvy   
2547      N      M  12/25/1946 0:00   Buffett     Jimmy   

                                title           date       state  \
358   Cofounder and Chairman Emeritus  4/4/2023 5:01  California   
521                               NaN  4/4/2023 5:01    Illinois   
963                               NaN  4/4/2023 5:01    Illinois   
1339         Investor, Philanthropist  4/4/2023 5:01        Ohio   
1733                              NaN  4/4/2023 5:01     Florida   
2167                              NaN  4/4/2023 5:01       Texas   
2547                         Musician  4/4/2023 5:01     Florida   

     residenceStateRegion  birthYear  birthMonth  birthDay  cpi_country  \
358                   NaN     1929.0         1.0       3.0       117.24   
521                   NaN     1941.0         9.0      28.0       117.24   
963                   NaN     1932.0         6.0      17.0       117.24   
1339                  NaN     1941.0         1.0      11.0       117.24   
1733                  NaN     1939.0         7.0      19.0       117.24   
2167                  NaN     1935.0        12.0       8.0       117.24   
2547                  NaN     1946.0        12.0      25.0       117.24   

      cpi_change_country           gdp_country  \
358                  7.5  $21,427,700,000,000    
521                  7.5  $21,427,700,000,000    
963                  7.5  $21,427,700,000,000    
1339                 7.5  $21,427,700,000,000    
1733                 7.5  $21,427,700,000,000    
2167                 7.5  $21,427,700,000,000    
2547                 7.5  $21,427,700,000,000    

      gross_tertiary_education_enrollment  \
358                                  88.2   
521                                  88.2   
963                                  88.2   
1339                                 88.2   
1733                          

In [362]:
# Filling null values in the state and residenceStateRegion columns where country is 'United States'

df_billions_na.loc[b_mask_1, ['state', 'residenceStateRegion']] = 'Unknown'
df_billions_na.loc[b_mask_2, 'residenceStateRegion'] = 'Unknown'

# Displaying the columns of interest in the filtered dataset to verify changes 

display(df_billions_na[['country', 'state', 'residenceStateRegion']][b_mask_1])
display(df_billions_na[['country', 'state', 'residenceStateRegion']][b_mask_2])

# Counting again the number of null values in the country, state and residenceStateRegion columns

print((df_billions_na['country']!='United States').sum())
print(df_billions_na['state'].isna().sum())
print(df_billions_na['residenceStateRegion'].isna().sum())




country    state residenceStateRegion
700  United States  Unknown              Unknown

country       state residenceStateRegion
358   United States  California              Unknown
521   United States    Illinois              Unknown
963   United States    Illinois              Unknown
1339  United States        Ohio              Unknown
1733  United States     Florida              Unknown
2167  United States       Texas              Unknown
2547  United States     Florida              Unknown

1886
1886
1886


In [363]:
# Creating filtered datasets to see null values in the selected columns

b_mask_3 = ((df_billions_na['state'].isna()) & (df_billions_na['country'] != 'United States'))
b_mask_4 = ((df_billions_na['residenceStateRegion'].isna()) & (df_billions_na['country'] != 'United States'))

# Filling null values in the state and residenceStateRegion columns where country is not 'United States'

df_billions_na.loc[b_mask_3, ['state', 'residenceStateRegion']] = 'No subdivisions info'
df_billions_na.loc[b_mask_4, ['state', 'residenceStateRegion']] = 'No subdivisions info'

# Displaying the columns of interest in the filtered dataset to verify changes 

display(df_billions_na[['country', 'state', 'residenceStateRegion']][b_mask_3])
display(df_billions_na[['country', 'state', 'residenceStateRegion']][b_mask_4])

# Counting again the number of null values in the country, state and residenceStateRegion columns

print((df_billions_na['country']!='United States').sum())
print(df_billions_na['state'].isna().sum())
print(df_billions_na['residenceStateRegion'].isna().sum())

country                 state  residenceStateRegion
0          France  No subdivisions info  No subdivisions info
7          Mexico  No subdivisions info  No subdivisions info
8           India  No subdivisions info  No subdivisions info
10         France  No subdivisions info  No subdivisions info
12          Spain  No subdivisions info  No subdivisions info
...           ...                   ...                   ...
2634        China  No subdivisions info  No subdivisions info
2635        China  No subdivisions info  No subdivisions info
2637        China  No subdivisions info  No subdivisions info
2638        China  No subdivisions info  No subdivisions info
2639  Philippines  No subdivisions info  No subdivisions info

[1886 rows x 3 columns]

country                 state  residenceStateRegion
0          France  No subdivisions info  No subdivisions info
7          Mexico  No subdivisions info  No subdivisions info
8           India  No subdivisions info  No subdivisions info
10         France  No subdivisions info  No subdivisions info
12          Spain  No subdivisions info  No subdivisions info
...           ...                   ...                   ...
2634        China  No subdivisions info  No subdivisions info
2635        China  No subdivisions info  No subdivisions info
2637        China  No subdivisions info  No subdivisions info
2638        China  No subdivisions info  No subdivisions info
2639  Philippines  No subdivisions info  No subdivisions info

[1886 rows x 3 columns]

1886
0
0


1. It's clear that rows whose `country` attribute is 'United States' have a null value in the `state` and `residenceStateRegion` because the counts are almost exact to each other (1,886 rows with a `country` attribute other than 'United States vs 1,887 rows with null values in the `state` attribute and 1,893 in the `residenceStateRegion` attribute.)

2. There are some rows whose `country` attribute is 'United States' and have null values in the related columns (1 in the `state` column and 7 in the `residenceStateRegion` column)..

3. For the rows whose `country` is 'United States' the null values in the `country` and `residenceStateRegion`have been changed to 'Unknown' whereas in the other cases, the string selected is 'No subdivisions info' to make it clear the dataset only contains information in this columns for United States.

Addressing null values in `organization`and `title` columns



In [364]:
df_billions_na.isna().sum().sort_values(ascending=False)

organization                                  2315
title                                         2301
cpi_country                                    184
cpi_change_country                             184
tax_revenue_country_country                    183
total_tax_rate_country                         182
life_expectancy_country                        182
gross_tertiary_education_enrollment            182
gross_primary_education_enrollment_country     181
latitude_country                               164
population_country                             164
gdp_country                                    164
longitude_country                              164
birthYear                                       76
birthMonth                                      76
birthDay                                        76
birthDate                                       76
city                                            72
age                                             65
country                        

In [365]:
print(df_billions_na['organization'].nunique())
print(df_billions_na['title'].nunique())

display((df_billions_na['organization'].unique()))
display((df_billions_na['title'].unique()))

294
97


array(['LVMH Moët Hennessy Louis Vuitton', 'Tesla', 'Amazon', 'Oracle',
       'Berkshire Hathaway Inc. (Cl A)',
       'Bill & Melinda Gates Foundation', 'Bloomberg', 'América Móvil',
       'Reliance Industries', 'Los Angeles Clippers', nan, 'Alphabet',
       'Meta Platforms', 'Koch Industries, Inc.',
       'Arvest Bank Group, Inc.', 'Walmart',
       'Crystal Bridges Museum of American Art',
       'Thomson Reuters Corporation', 'Dell Inc.', 'Nike', 'ByteDance',
       'CK Hutchison Holdings', 'Tencent Holdings', 'Citadel LLC',
       'Renaissance Technologies Corp.', 'Blackstone Group',
       'Hancock Prospecting', 'SoftBank Group Corp.',
       'Fidelity Investments', 'Nvidia', 'The Estée Lauder Companies',
       'Bridgewater Associates', 'Continental Resources Inc. ',
       'Appaloosa Management', 'ArcelorMittal (ADR)',
       'Point72 Asset Management', 'Icahn Capital Management',
       'Irvine Company', 'Menard, Inc.', 'News Corp Class A',
       'Hennes & Mauritz Unspons

array(['Chairman and CEO', 'CEO', 'Chairman and Founder',
       'CTO and Founder', 'Cochair', 'Honorary Chairman',
       'Founder and Chairman', 'Owner', nan, 'Cofounder and board member',
       'Cofounder', 'Director', 'Philanthropist', 'Chairman', 'Founder',
       'Senior Advisor', 'Founder & CEO', 'Executive Chairman',
       'CEO & President', 'Chairman Emeritus',
       'Founder & Co-Chief Investment Officer', 'President and Founder',
       'Founder ', 'Investor, Philanthropist', 'Chief Executive Officer',
       'Investor', 'CEO, cofounder', 'President and General Manager',
       'Chairman & CEO', 'Chairman and Cofounder', 'Founder and CEO',
       'Entrepreneur', 'Founder, Chairman and CEO', 'CEO and Cofounder',
       'Founder Chairman', 'Professor',
       'Cofounder, Chief Development Officer and Chairman',
       'Co-founder, ex chairman of the board',
       'Cofounder, Chief Technology Officer and Chairman',
       'Cofounder & Chair of Airbnb.org', 'Co-Chair and Co-

There are 294 and 97 different values in the ``organization`` and ``title`` columns. Despite of this, more than 70% of the values in these columns are null. The best option is to set the null values to 'Unknown' in both columns

In [366]:
# Filling null values in the organization and title columns

df_billions_na.loc[df_billions_na['organization'].isna(), 'organization'] = 'Unknown'
df_billions_na.loc[df_billions_na['title'].isna(), 'title'] = 'Unknown'

# Printing the null value count to verify changes

print(df_billions_na['organization'].isna().sum())
print(df_billions_na['title'].isna().sum())


0
0


# **Until here the code is OK**

Addressing impaired null values in `cpi_country `and `cpi_change_country` columns

In [367]:
# Ensure that null values for both columns are located in the same rows

b_mask_5 = (df_billions_na['cpi_country'].notna()) & (df_billions_na['cpi_change_country'].isna())
df_billions_na[b_mask_5]

# Filling the null values in both columns

df_billions_na[['cpi_country', 'cpi_change_country']] = df_billions_na[['cpi_country', 'cpi_change_country']].fillna('No CPI info')

# Counting the null values in the selected columns

print(df_billions_na['cpi_country'].isna().sum())
print(df_billions_na['cpi_change_country'].isna().sum())






0
0


Addressing impaired null values in `tax_revenue_country_country` and `total_tax_rate_country` columns

In [368]:
# Ensure that null values for both columns are located in the same rows

b_mask_6 = (df_billions_na['total_tax_rate_country'].notna()) & (df_billions_na['tax_revenue_country_country'].isna())
df_billions_na[['total_tax_rate_country', 'tax_revenue_country_country']][b_mask_6]

# Setup the total_tax_rate_country column value to '0.0' in the mismatched row

df_billions_na.loc[b_mask_6, ['total_tax_rate_country', 'tax_revenue_country_country']] = 0

# Print the selected data to verify changes

df_billions_na[df_billions_na['country'] == 'Liechtenstein'][['total_tax_rate_country', 'tax_revenue_country_country']]


total_tax_rate_country  tax_revenue_country_country
1365                     0.0                          0.0

In [369]:
df_billions_na.isna().sum()

rank                                            0
finalWorth                                      0
category                                        0
personName                                      0
age                                            65
country                                        38
city                                           72
source                                          0
industries                                      0
countryOfCitizenship                            0
organization                                    0
selfMade                                        0
status                                          0
gender                                          0
birthDate                                      76
lastName                                        0
firstName                                       3
title                                           0
date                                            0
state                                           0


Addressing impaired null values in `gross_tertiary_education_enrollment` and `gross_primary_education_enrollment_country`

In [370]:
# Ensure that null values for both columns are located in the same rows

b_mask_7 = (df_billions_na['gross_primary_education_enrollment_country'].notna()) & (df_billions_na['gross_tertiary_education_enrollment'].isna())
df_billions_na[['gross_primary_education_enrollment_country', 'gross_tertiary_education_enrollment']][b_mask_7]

# Setup the gross_primary_education_enrollment_country column value to '0.0' in the mismatched row

df_billions_na.loc[b_mask_7, ['gross_primary_education_enrollment_country', 'gross_tertiary_education_enrollment']] = 0.0

# Print the selected data to verify changes

df_billions_na[df_billions_na['country'] == 'Andorra'][['gross_primary_education_enrollment_country', 'gross_tertiary_education_enrollment']]


gross_primary_education_enrollment_country  \
2002                                         0.0   

      gross_tertiary_education_enrollment  
2002                                  0.0

In [371]:
df_billions_na.isna().sum()

rank                                            0
finalWorth                                      0
category                                        0
personName                                      0
age                                            65
country                                        38
city                                           72
source                                          0
industries                                      0
countryOfCitizenship                            0
organization                                    0
selfMade                                        0
status                                          0
gender                                          0
birthDate                                      76
lastName                                        0
firstName                                       3
title                                           0
date                                            0
state                                           0


Addressing null values in `first_name` column

In [372]:
# Creating filtered datasets to see null values in the selected columns

b_mask_8 = (df_billions_na['personName'].notna()) & (df_billions_na['firstName'].isna())
df_billions_na[b_mask_8]

name_mapping = {
    'Tahir': 'Muhammad',
    'Jay-Z': 'Shawn',
    'Rihanna': 'Robyn'
}

for last_name, first_name in name_mapping.items():
    df_billions_na.loc[df_billions_na['lastName'] == last_name, 'firstName'] = first_name

df_billions_na['firstName'].isna().sum()

0

##### **Key takeaways from this subsection**
1. 


In [373]:
df_billions_na.isna().sum()

rank                                            0
finalWorth                                      0
category                                        0
personName                                      0
age                                            65
country                                        38
city                                           72
source                                          0
industries                                      0
countryOfCitizenship                            0
organization                                    0
selfMade                                        0
status                                          0
gender                                          0
birthDate                                      76
lastName                                        0
firstName                                       0
title                                           0
date                                            0
state                                           0


### Part 2.1. - Dataset structural enhacement

Column renaming

In [374]:
# Making a copy of the df_billions_na dataset to begin structural improvements

df_billions_cleaned = df_billions_na.copy()


df_billions_cleaned.head(5)

rank  finalWorth               category                personName   age  \
0     1      211000       Fashion & Retail  Bernard Arnault & family  74.0   
1     2      180000             Automotive                 Elon Musk  51.0   
2     3      114000             Technology                Jeff Bezos  59.0   
3     4      107000             Technology             Larry Ellison  78.0   
4     5      106000  Finance & Investments            Warren Buffett  92.0   

         country    city              source             industries  \
0         France   Paris                LVMH       Fashion & Retail   
1  United States  Austin       Tesla, SpaceX             Automotive   
2  United States  Medina              Amazon             Technology   
3  United States   Lanai              Oracle             Technology   
4  United States   Omaha  Berkshire Hathaway  Finance & Investments   

  countryOfCitizenship                      organization  selfMade status  \
0               France  LVMH Moët Hennessy Louis Vuitton     False      U   
1        United States                             Tesla      True      D   
2        United States                            Amazon      True      D   
3        United States                            Oracle      True      U   
4        United States    Berkshire Hathaway Inc. (Cl A)      True      D   

  gender       birthDate lastName firstName                 title  \
0      M   3/5/1949 0:00  Arnault   Bernard      Chairman and CEO   
1      M  6/28/1971 0:00     Musk      Elon                   CEO   
2      M  1/12/1964 0:00    Bezos      Jeff  Chairman and Founder   
3      M  8/17/1944 0:00  Ellison     Larry       CTO and Founder   
4      M  8/30/1930 0:00  Buffett    Warren                   CEO   

            date                 state  residenceStateRegion  birthYear  \
0  4/4/2023 5:01  No subdivisions info  No subdivisions info     1949.0   
1  4/4/2023 5:01                 Texas                 South     1971.0   
2  4/4/2023 5:01            Washington                  West     1964.0   
3  4/4/2023 5:01                Hawaii                  West     1944.0   
4  4/4/2023 5:01              Nebraska               Midwest     1930.0   

   birthMonth  birthDay cpi_country cpi_change_country           gdp_country  \
0         3.0       5.0      110.05                1.1   $2,715,518,274,227    
1         6.0      28.0      117.24                7.5  $21,427,700,000,000    
2         1.0      12.0      117.24                7.5  $21,427,700,000,000    
3         8.0      17.0      117.24                7.5  $21,427,700,000,000    
4         8.0      30.0      117.24                7.5  $21,427,700,000,000    

   gross_tertiary_education_enrollment  \
0                                 65.6   
1                                 88.2   
2                                 88.2   
3                                 88.2   
4                                 88.2   

   gross_primary_education_enrollment_country  life_expectancy_country  \
0                                       102.5                     82.5   
1                                       101.8                     78.5   
2                                       101.8                     78.5   
3                                       101.8                     78.5   
4                                       101.8                     78.5   

   tax_revenue_country_country  total_tax_rate_country  population_country  \
0                         24.2                    60.7          67059887.0   
1                          9.6                    36.6         328239523.0   
2                          9.6                    36.6         328239523.0   
3                          9.6                    36.6         328239523.0   
4                          9.6                    36.6         328239523.0   

   latitude_country  longitude_country  
0         46.227638           2.213749  
1         37.090240         -95.712891  
2      

There are two columns that may contain the same information: `category` and `ìndustries`. A boolean mask can be created to display how many rows (if any) don't contain the same information. If there is no result, both columns contain the same information and one can be dropped.

In [375]:
# Creating a Boolean mask to find rows where 'category' and 'industries' columns have different values

b_mask_not_equal = df_billions_cleaned['category'] != df_billions_cleaned['industries']

df_billions_cleaned[b_mask_not_equal]

Empty DataFrame
Columns: [rank, finalWorth, category, personName, age, country, city, source, industries, countryOfCitizenship, organization, selfMade, status, gender, birthDate, lastName, firstName, title, date, state, residenceStateRegion, birthYear, birthMonth, birthDay, cpi_country, cpi_change_country, gdp_country, gross_tertiary_education_enrollment, gross_primary_education_enrollment_country, life_expectancy_country, tax_revenue_country_country, total_tax_rate_country, population_country, latitude_country, longitude_country]
Index: []

From the code above, it's clear that both columns contain the same information. We can also investigate how many values exist for each different element in both columns using `value_counts`

In [376]:
# Count the different values of both columns to ensure they have the same information

print(df_billions_cleaned['category'].value_counts())
print('\n', df_billions_cleaned['industries'].value_counts())

category
Finance & Investments         372
Manufacturing                 324
Technology                    314
Fashion & Retail              266
Food & Beverage               212
Healthcare                    201
Real Estate                   193
Diversified                   187
Energy                        100
Media & Entertainment          91
Metals & Mining                74
Automotive                     73
Service                        53
Construction & Engineering     45
Logistics                      40
Sports                         39
Telecom                        31
Gambling & Casinos             25
Name: count, dtype: int64

 industries
Finance & Investments         372
Manufacturing                 324
Technology                    314
Fashion & Retail              266
Food & Beverage               212
Healthcare                    201
Real Estate                   193
Diversified                   187
Energy                        100
Media & Entertainment          91


We can conclude that `category` and `ìndustries` columns have the same values, so we can drop one of them. Before doing it, they will be renamed because some other columns may be dropped as well and only one piece of code will be doing the removal to finish data cleaning.

In [377]:
df_billions_cleaned.rename({'category': 'industry', 'industries': 'to_be_deleted_1'}, axis=1, inplace = True)

df_billions_cleaned.head(3)

rank  finalWorth          industry                personName   age  \
0     1      211000  Fashion & Retail  Bernard Arnault & family  74.0   
1     2      180000        Automotive                 Elon Musk  51.0   
2     3      114000        Technology                Jeff Bezos  59.0   

         country    city         source   to_be_deleted_1  \
0         France   Paris           LVMH  Fashion & Retail   
1  United States  Austin  Tesla, SpaceX        Automotive   
2  United States  Medina         Amazon        Technology   

  countryOfCitizenship                      organization  selfMade status  \
0               France  LVMH Moët Hennessy Louis Vuitton     False      U   
1        United States                             Tesla      True      D   
2        United States                            Amazon      True      D   

  gender       birthDate lastName firstName                 title  \
0      M   3/5/1949 0:00  Arnault   Bernard      Chairman and CEO   
1      M  6/28/1971 0:00     Musk      Elon                   CEO   
2      M  1/12/1964 0:00    Bezos      Jeff  Chairman and Founder   

            date                 state  residenceStateRegion  birthYear  \
0  4/4/2023 5:01  No subdivisions info  No subdivisions info     1949.0   
1  4/4/2023 5:01                 Texas                 South     1971.0   
2  4/4/2023 5:01            Washington                  West     1964.0   

   birthMonth  birthDay cpi_country cpi_change_country           gdp_country  \
0         3.0       5.0      110.05                1.1   $2,715,518,274,227    
1         6.0      28.0      117.24                7.5  $21,427,700,000,000    
2         1.0      12.0      117.24                7.5  $21,427,700,000,000    

   gross_tertiary_education_enrollment  \
0                                 65.6   
1                                 88.2   
2                                 88.2   

   gross_primary_education_enrollment_country  life_expectancy_country  \
0                                       102.5                     82.5   
1                                       101.8                     78.5   
2                                       101.8                     78.5   

   tax_revenue_country_country  total_tax_rate_country  population_country  \
0                         24.2                    60.7          67059887.0   
1                          9.6                    36.6         328239523.0   
2                          9.6                    36.6         328239523.0   

   latitude_country  longitude_country  
0         46.227638           2.213749  
1         37.090240         -95.712891  
2         37.090240         -95.712891

### Part 2.2. - Data Quality improvement

Data cleaning

1. Check for duplicate values - OK
2. Data type adjustment - OK
3. Data quality inspection - OK
4. Feature engineering - 
5. Advanced handling of missing values - 
6. Outliers inspection
7. Dropping columns and creating the definitive dataset for analysis - 

Looking for duplicate values in the dataset

In [378]:
# Check for duplicated rows in the dataset

df_billions_cleaned.duplicated().value_counts()

False    2640
Name: count, dtype: int64

The dataset doesn't contain any duplicate values

Data types adjustment

There are several columns that contain datatypes not suited for a meaningful analysis. They all fall into one of this situations:
1. Numeric values that are displayed as `float64`, where `Int64` should be the correct data type. This is the case for ``age``, `birthYear`, `birthMonth`, `birthDay` and `population_country` columns.
2. Date values that should be `datetime64[ns]` that are displayed as ``object``. This is the case for ``date`` and ``birthDate`` columns.
3. Numeric values that are displayed as ``object`` because they have symbols and special characters. This is the case for ``country_gdp`` column.

Each of these cases need to be address to ensure that columns have the most suited data type for conducting analysis.

In [379]:
display(df_billions_cleaned.head(3))

rank  finalWorth          industry                personName   age  \
0     1      211000  Fashion & Retail  Bernard Arnault & family  74.0   
1     2      180000        Automotive                 Elon Musk  51.0   
2     3      114000        Technology                Jeff Bezos  59.0   

         country    city         source   to_be_deleted_1  \
0         France   Paris           LVMH  Fashion & Retail   
1  United States  Austin  Tesla, SpaceX        Automotive   
2  United States  Medina         Amazon        Technology   

  countryOfCitizenship                      organization  selfMade status  \
0               France  LVMH Moët Hennessy Louis Vuitton     False      U   
1        United States                             Tesla      True      D   
2        United States                            Amazon      True      D   

  gender       birthDate lastName firstName                 title  \
0      M   3/5/1949 0:00  Arnault   Bernard      Chairman and CEO   
1      M  6/28/1971 0:00     Musk      Elon                   CEO   
2      M  1/12/1964 0:00    Bezos      Jeff  Chairman and Founder   

            date                 state  residenceStateRegion  birthYear  \
0  4/4/2023 5:01  No subdivisions info  No subdivisions info     1949.0   
1  4/4/2023 5:01                 Texas                 South     1971.0   
2  4/4/2023 5:01            Washington                  West     1964.0   

   birthMonth  birthDay cpi_country cpi_change_country           gdp_country  \
0         3.0       5.0      110.05                1.1   $2,715,518,274,227    
1         6.0      28.0      117.24                7.5  $21,427,700,000,000    
2         1.0      12.0      117.24                7.5  $21,427,700,000,000    

   gross_tertiary_education_enrollment  \
0                                 65.6   
1                                 88.2   
2                                 88.2   

   gross_primary_education_enrollment_country  life_expectancy_country  \
0                                       102.5                     82.5   
1                                       101.8                     78.5   
2                                       101.8                     78.5   

   tax_revenue_country_country  total_tax_rate_country  population_country  \
0                         24.2                    60.7          67059887.0   
1                          9.6                    36.6         328239523.0   
2                          9.6                    36.6         328239523.0   

   latitude_country  longitude_country  
0         46.227638           2.213749  
1         37.090240         -95.712891  
2         37.090240         -95.712891

In [380]:
# Changing age, birthYear, birthMonth, and birthDay to integers

int_columns = ['age', 'birthYear', 'birthMonth', 'birthDay']

# Converting selected columns to int, keeping missing values

df_billions_cleaned[int_columns] = df_billions_cleaned[int_columns].astype('Int64')

# Changing population_country column to integer

df_billions_cleaned['population_country'] = df_billions_cleaned['population_country'].astype('Int64')


In [381]:


df_billions_cleaned['date'] = pd.to_datetime(df_billions_cleaned['date']).dt.strftime('%Y/%m/%d')
df_billions_cleaned['date'] = pd.to_datetime(df_billions_cleaned['date'], format='%Y/%m/%d')

df_billions_cleaned['birthDate'] = pd.to_datetime(df_billions_cleaned['birthDate']).dt.strftime('%Y/%m/%d')
df_billions_cleaned['birthDate'] = pd.to_datetime(df_billions_cleaned['birthDate'], format='%Y/%m/%d')


In [382]:
print(df_billions_cleaned['date'].unique())
print(df_billions_cleaned['birthDate'].unique())

<DatetimeArray>
['2023-04-04 00:00:00']
Length: 1, dtype: datetime64[ns]
<DatetimeArray>
['1949-03-05 00:00:00', '1971-06-28 00:00:00', '1964-01-12 00:00:00',
 '1944-08-17 00:00:00', '1930-08-30 00:00:00', '1955-10-28 00:00:00',
 '1942-02-14 00:00:00', '1940-01-28 00:00:00', '1957-04-19 00:00:00',
 '1956-03-24 00:00:00',
 ...
 '1945-05-23 00:00:00', '1950-08-05 00:00:00', '1988-03-21 00:00:00',
 '1963-04-17 00:00:00', '1969-07-17 00:00:00', '1971-12-14 00:00:00',
 '1943-03-10 00:00:00', '1962-12-18 00:00:00', '1951-08-21 00:00:00',
 '1956-11-01 00:00:00']
Length: 2061, dtype: datetime64[ns]


In [383]:
# Remove '$' sign from gdp_country and cast values as integers

df_billions_cleaned['gdp_country'] = df_billions_cleaned['gdp_country'].replace('[\$,]', '', regex=True).astype('float64').astype('Int64')


In [384]:
# Printing the data types with dtypes to verify conversion

df_billions_cleaned.dtypes

rank                                                   int64
finalWorth                                             int64
industry                                              object
personName                                            object
age                                                    Int64
country                                               object
city                                                  object
source                                                object
to_be_deleted_1                                       object
countryOfCitizenship                                  object
organization                                          object
selfMade                                                bool
status                                                object
gender                                                object
birthDate                                     datetime64[ns]
lastName                                              object
firstName               

Data quality inspection

Column `status` tells us whether the billionaire is self-made (D) or their fortune have any other origin (U). The `self-made` column indicates whether the billionaire is self-made with True/False.

In theory, the number of values in the `status` column that indicates a self-made fortune (D) should be equal to the number of True values in the `selfMade` column.

In [385]:
display(df_billions_cleaned['status'].value_counts())
display(df_billions_cleaned['selfMade'].value_counts())

status
D                       1223
U                        855
E                        268
N                        150
Split Family Fortune      79
R                         65
Name: count, dtype: int64

selfMade
True     1812
False     828
Name: count, dtype: int64

After using the `value_counts()` method in both columns it's clear that not these values don't match, but that there are more categories in the `status` column that the ones mentioned in the data dictionary.

Although a comparison between self-made vs inherited wealth could drive meaningful insights, both columns have inconsistencies and should not be used to perform any analysis based on them.

Inspecting different columns to look for wrong data

In [386]:
display(df_billions_cleaned['industry'].unique())
display(df_billions_cleaned['country'].unique())
display(df_billions_cleaned['countryOfCitizenship'].unique())
display(df_billions_cleaned['gender'].unique())


array(['Fashion & Retail', 'Automotive', 'Technology',
       'Finance & Investments', 'Media & Entertainment', 'Telecom',
       'Diversified', 'Food & Beverage', 'Logistics',
       'Gambling & Casinos', 'Manufacturing', 'Real Estate',
       'Metals & Mining', 'Energy', 'Healthcare', 'Service',
       'Construction & Engineering', 'Sports'], dtype=object)

array(['France', 'United States', 'Mexico', 'India', 'Spain', 'China',
       'Canada', 'Germany', 'Switzerland', 'Belgium', 'Hong Kong',
       'Austria', 'Japan', 'United Kingdom', 'Australia', 'Indonesia',
       'United Arab Emirates', 'Russia', 'Chile', 'Monaco',
       'Czech Republic', 'Sweden', nan, 'Thailand', 'Uzbekistan',
       'Singapore', 'Nigeria', 'Israel', 'Italy', 'South Africa',
       'Brazil', 'Malaysia', 'South Korea', 'New Zealand', 'Philippines',
       'Taiwan', 'Norway', 'Egypt', 'Denmark', 'Eswatini (Swaziland)',
       'Colombia', 'Netherlands', 'Poland', 'Bahamas', 'Ukraine',
       'Cayman Islands', 'Greece', 'Turkey', 'Argentina', 'Georgia',
       'Portugal', 'Kazakhstan', 'Algeria', 'Vietnam', 'Latvia',
       'Finland', 'Bermuda', 'Luxembourg', 'British Virgin Islands',
       'Cambodia', 'Lebanon', 'Oman', 'Ireland', 'Cyprus', 'Guernsey',
       'Liechtenstein', 'Turks and Caicos Islands', 'Romania', 'Qatar',
       'Uruguay', 'Nepal', 'Slovakia', 'Mo

array(['France', 'United States', 'Mexico', 'India', 'Spain', 'China',
       'Canada', 'Germany', 'Italy', 'Hong Kong', 'Austria', 'Japan',
       'Switzerland', 'Australia', 'Indonesia', 'Russia', 'Chile',
       'United Kingdom', 'Israel', 'Brazil', 'Czech Republic',
       'Singapore', 'Sweden', 'Thailand', 'Netherlands', 'Nigeria',
       'Cyprus', 'Malaysia', 'United Arab Emirates', 'South Africa',
       'New Zealand', 'Philippines', 'Monaco', 'Belgium', 'South Korea',
       'Taiwan', 'Norway', 'Egypt', 'Denmark', 'Ireland',
       'Eswatini (Swaziland)', 'Colombia', 'Poland', 'Ukraine', 'Greece',
       'Turkey', 'Argentina', 'Georgia', 'Portugal', 'Kazakhstan',
       'Algeria', 'Venezuela', 'Vietnam', 'Finland', 'Belize', 'Lebanon',
       'Oman', 'Iceland', 'Guernsey', 'Liechtenstein', 'Bulgaria',
       'Romania', 'Zimbabwe', 'Qatar', 'Nepal', 'Slovakia', 'Morocco',
       'Hungary', 'Tanzania', 'Peru', 'Barbados', 'Macau', 'Estonia',
       'St. Kitts and Nevis', 'Armenia

array(['M', 'F'], dtype=object)

After looking at the different values in key string columns that are going to be used to perform analysis, the conclusion is that data is correct and don't contain wrong entries.

In [387]:
display(df_billions_cleaned['birthYear'].unique())
display(df_billions_cleaned['birthMonth'].unique())
display(df_billions_cleaned['birthDay'].unique())

<IntegerArray>
[1949, 1971, 1964, 1944, 1930, 1955, 1942, 1940, 1957, 1956, 1953, 1973, 1936,
 1954, 1984, 1935, 1962, 1948, 1965, 1938, 1939, 1937, 1928, 1945, 1968, 1992,
 1969, 1951, 1980, 1958, 1947, 1972, 1966, 1970, 1941, 1961, 1943, 1986, 1963,
 1933, 1950, 1952, 1932, 1931, 1967, <NA>, 1946, 1978, 1927, 1929, 1976, 1959,
 1923, 1960, 1934, 1977, 1979, 1982, 1981, 1975, 1974, 1983, 1985, 1926, 1990,
 1988, 1989, 1987, 2004, 1995, 2001, 1993, 1924, 2002, 1996, 1925, 1921, 1994]
Length: 78, dtype: Int64

<IntegerArray>
[3, 6, 1, 8, 10, 2, 4, 7, 12, 5, 11, 9, <NA>]
Length: 13, dtype: Int64

<IntegerArray>
[   5,   28,   12,   17,   30,   14,   19,   24,   10,   26,   21,    1,    7,
   27,   23,    2,   15,   13,   29,    9,   20,   25,   18,    8,    3,   11,
   16,   22,    4, <NA>,    6,   31]
Length: 32, dtype: Int64

Columns with parts of the birth date are correct, with no weird or wrong data.

In [388]:
display(df_billions_cleaned['state'].unique())
display(df_billions_cleaned['residenceStateRegion'].unique())

array(['No subdivisions info', 'Texas', 'Washington', 'Hawaii',
       'Nebraska', 'New York', 'California', 'Kansas', 'Arkansas',
       'Oregon', 'Virginia', 'Wyoming', 'Nevada', 'Florida',
       'Pennsylvania', 'Massachusetts', 'Illinois', 'Tennessee',
       'Connecticut', 'Oklahoma', 'Michigan', 'Wisconsin', 'Colorado',
       'Indiana', 'New Hampshire', 'Georgia', 'Missouri', 'New Jersey',
       'North Carolina', 'Iowa', 'Kentucky', 'Maryland', 'Montana',
       'Ohio', 'South Carolina', 'Arizona', 'Louisiana', 'Unknown',
       'Utah', 'Rhode Island', 'Idaho', 'U.S. Virgin Islands',
       'Minnesota', 'Maine', 'Mississippi', 'South Dakota', 'Alabama'],
      dtype=object)

array(['No subdivisions info', 'South', 'West', 'Midwest', 'Northeast',
       'Unknown', 'U.S. Territories'], dtype=object)

Columns displaying information about subdivisions are also OK, with no wrong data in them.

### Part 2.3. - Feature engineering

Creating a new `continent` column will serve to fill null values in columns where locations are important. This is the case of the economic-related indicators such as education enrollment and CPI. Although null values could be filled using the mean or the median of all values, an alternative approach coule be to imput missing data only by taking into account the values that can be assumed to be close to the null value that is going to be filled.

**Example**: The value of g_tertiary_education_enrollment is missed in Andorra. One solution could be use the mean or the median of all the values in the column. However, another solution is to only use the mean/median values of countries that belong to Europe. This is because other countries may have significant different values for this column and using all of them to fill the null would result in a value that is not representative.

In [389]:

# Create an empty column for 'continent'
df_billions_cleaned['continent'] = ''

# Define lists of countries for each continent
africa_countries = ['Eswatini (Swaziland)', 'Morocco', 'Nigeria', 'South Africa', 'Tanzania', 'Egypt', 'Algeria']

asia_countries = ['Bahrain', 'Cambodia', 'China', 'Hong Kong', 'India', 'Indonesia', 'Israel', 'Japan', 'Kazakhstan', 'Lebanon', 'Malaysia', 'Nepal', 'Oman', 'Philippines', 'Qatar', 'Singapore', 'South Korea', 'Taiwan', 'Thailand', 'Turkey', 'United Arab Emirates', 'Uzbekistan', 'Vietnam']

europe_countries = ['Andorra', 'Armenia', 'Austria', 'Belgium', 'Cyprus', 'Czech Republic', 'Denmark', 'Finland', 'France', 'Georgia', 'Germany', 'Greece', 'Guernsey', 'Hungary', 'Ireland', 'Italy', 'Latvia', 'Liechtenstein', 'Luxembourg', 'Monaco', 'Netherlands', 'Norway', 'Poland', 'Portugal', 'Romania', 'Russia', 'Slovakia', 'Spain', 'Sweden', 'Switzerland', 'Ukraine', 'United Kingdom']

n_america_countries = ['Bahamas', 'Bermuda', 'British Virgin Islands', 'Canada', 'Cayman Islands', 'Mexico', 'Turks and Caicos Islands', 'United States']

s_america_countries = ['Argentina', 'Brazil', 'Chile', 'Colombia', 'Peru', 'Uruguay']

oceania_countries = ['Australia', 'New Zealand']

# Assign continents based on country lists
df_billions_cleaned.loc[df_billions_cleaned['country'].isin(africa_countries), 'continent'] = 'Africa'
df_billions_cleaned.loc[df_billions_cleaned['country'].isin(asia_countries), 'continent'] = 'Asia'
df_billions_cleaned.loc[df_billions_cleaned['country'].isin(europe_countries), 'continent'] = 'Europe'
df_billions_cleaned.loc[df_billions_cleaned['country'].isin(n_america_countries), 'continent'] = 'North America'
df_billions_cleaned.loc[df_billions_cleaned['country'].isin(s_america_countries), 'continent'] = 'South America'
df_billions_cleaned.loc[df_billions_cleaned['country'].isin(oceania_countries), 'continent'] = 'Oceania'


In [390]:
# Displaying both columns to see results

df_billions_cleaned[['country', 'continent']]

# Displaying the number of empty values of the new column to ensure it has the same amount as the null values in the  country column

display(df_billions_cleaned['country'].isna().sum())

(df_billions_cleaned['continent'] == '').sum()



38

38

In [391]:
df_billions_cleaned.isna().sum()

rank                                            0
finalWorth                                      0
industry                                        0
personName                                      0
age                                            65
country                                        38
city                                           72
source                                          0
to_be_deleted_1                                 0
countryOfCitizenship                            0
organization                                    0
selfMade                                        0
status                                          0
gender                                          0
birthDate                                      76
lastName                                        0
firstName                                       0
title                                           0
date                                            0
state                                           0


Advanced null values addressing

Addressing null and missing values in `country`, `city` and ``continent`` columns

In [392]:
df_billions_cleaned['country'] = df_billions_cleaned['country'].fillna('Unknown')
df_billions_cleaned['city'] = df_billions_cleaned['city'].fillna('Unknown')
df_billions_cleaned['continent'] = df_billions_cleaned['continent'].replace('', 'Unknown')


Addressing null values for `life_expectancy_country` column

In [393]:
# Finding countries and subdivisions with null values:

print(df_billions[df_billions['life_expectancy_country'].isnull()].groupby('country').size().reset_index(name='no life expectancy').sort_values(by='no life expectancy', ascending=False))

                     country  no life expectancy
7                  Hong Kong                  68
10                    Taiwan                  43
9                     Monaco                  17
8                    Ireland                   4
4             Cayman Islands                   3
1                    Bahamas                   2
2                    Bermuda                   2
0                    Andorra                   1
3     British Virgin Islands                   1
5       Eswatini (Swaziland)                   1
6                   Guernsey                   1
11  Turks and Caicos Islands                   1


In [394]:
# Creating a dictionary to fill null values for the column

life_exp_dict = {
    'Hong Kong': 85.5,
    'Taiwan': 80.7,
    'Monaco': 85.9,
    'Ireland': 82.1,
    'Cayman Islands': 82.1,
    'Bahamas': 71.6,
    'Bermuda': 79.3,
    'Andorra': 83.3,
    'British Virgin Islands': 74.5,
    'Eswatini (Swaziland)': 57.1,
    'Guernsey': 81.3,
    'Turks and Caicos Islands': 74.6
}

# Fill null values in 'life_expectancy' column using the dictionary

df_billions_cleaned['life_expectancy_country'].fillna(df_billions_cleaned['country'].map(life_exp_dict), inplace=True)

# Printing the sum of null values verify it doesn't have nulls

print(df_billions_cleaned[df_billions_cleaned['life_expectancy_country'].isnull()].groupby('country').size().reset_index(name='no life expectancy').sort_values(by='no life expectancy', ascending=False))

   country  no life expectancy
0  Unknown                  38


Addressing null values in `gdp_country` column

In [395]:
print(df_billions_cleaned[df_billions_cleaned['gdp_country'].isnull()].groupby('country').size().reset_index(name='no GDP figures').sort_values(by='no GDP figures', ascending=False))

                     country  no GDP figures
6                  Hong Kong              68
8                     Taiwan              43
10                   Unknown              38
7                    Ireland               4
3             Cayman Islands               3
0                    Bahamas               2
1                    Bermuda               2
2     British Virgin Islands               1
4       Eswatini (Swaziland)               1
5                   Guernsey               1
9   Turks and Caicos Islands               1


In [396]:
# Creating a dictionary to fill null values for the column

gdp_dict = {
    'Hong Kong': 368911387845,
    'Taiwan': 774700000000,
    'Ireland': 513391778882,
    'Cayman Islands': 6028373513,
    'Bahamas': 11527600000,
    'Bermuda': 7127200000,
    'British Virgin Islands': 1120000000,
    'Eswatini (Swaziland)': 4850842572,
    'Guernsey': 4143608400,
    'Turks and Caicos Islands': 1044778790
}

# Fill null values in 'gdp_country' column using the dictionary

df_billions_cleaned['gdp_country'].fillna(df_billions_cleaned['country'].map(gdp_dict), inplace=True)

# Printing the sum of null values verify it doesn't have nulls

print(df_billions_cleaned[df_billions_cleaned['gdp_country'].isnull()].groupby('country').size().reset_index(name='no gdp figures').sort_values(by='no gdp figures', ascending=False))

   country  no gdp figures
0  Unknown              38


Addressing null values in `population_country` column

In [397]:
print(df_billions_cleaned[df_billions_cleaned['population_country'].isnull()].groupby('country').size().reset_index(name='no population figures').sort_values(by='no population figures', ascending=False))

                     country  no population figures
6                  Hong Kong                     68
8                     Taiwan                     43
10                   Unknown                     38
7                    Ireland                      4
3             Cayman Islands                      3
0                    Bahamas                      2
1                    Bermuda                      2
2     British Virgin Islands                      1
4       Eswatini (Swaziland)                      1
5                   Guernsey                      1
9   Turks and Caicos Islands                      1


In [398]:
# Creating a dictionary to fill null values for the column

pop_dict = {
    'Hong Kong': 7413100,
    'Taiwan': 24859912,
    'Ireland': 5033164,
    'Cayman Islands': 68136,
    'Bahamas': 407906,
    'Bermuda': 63764,
    'British Virgin Islands': 31122,
    'Eswatini (Swaziland)': 1192271,
    'Guernsey': 63463,
    'Turks and Caicos Islands': 45114
}

# Fill null values in 'gdp_country' column using the dictionary

df_billions_cleaned['population_country'].fillna(df_billions_cleaned['country'].map(pop_dict), inplace=True)

# Printing the sum of null values verify it doesn't have nulls

print(df_billions_cleaned[df_billions_cleaned['population_country'].isnull()].groupby('country').size().reset_index(name='no population figures').sort_values(by='no population figures', ascending=False))

   country  no population figures
0  Unknown                     38


Addressing null values in `longitude_country` and `latitude_country`

In [399]:
print(df_billions_cleaned[df_billions_cleaned['longitude_country'].isnull()].groupby('country').size().reset_index(name='no geographycal data').sort_values(by='no geographycal data', ascending=False))

                     country  no geographycal data
6                  Hong Kong                    68
8                     Taiwan                    43
10                   Unknown                    38
7                    Ireland                     4
3             Cayman Islands                     3
0                    Bahamas                     2
1                    Bermuda                     2
2     British Virgin Islands                     1
4       Eswatini (Swaziland)                     1
5                   Guernsey                     1
9   Turks and Caicos Islands                     1


In [400]:
# Creating two dictionaries to fill null values for the columns

lat_dict = {
    'Hong Kong': 22.396428,
    'Taiwan': 23.697810,
    'Ireland': 53.412910,
    'Cayman Islands': 19.513469,
    'Bahamas': 25.034280,
    'Bermuda': 32.321384,
    'British Virgin Islands': 18.420695,
    'Eswatini (Swaziland)': -26.522503,
    'Guernsey': 49.465691,
    'Turks and Caicos Islands': 21.694025
}

long_dict = {
    'Hong Kong': 114.109497,
    'Taiwan': 120.960515,
    'Ireland': -8.243890,
    'Cayman Islands': -80.566956,
    'Bahamas': -77.396280,
    'Bermuda': -64.757370,
    'British Virgin Islands': -64.639968,
    'Eswatini (Swaziland)': 31.465866,
    'Guernsey': -2.585278,
    'Turks and Caicos Islands': -71.797928
}

# Fill null values in 'latitude_country' and 'longitude_country' columns using the dictionaries

df_billions_cleaned['latitude_country'].fillna(df_billions_cleaned['country'].map(lat_dict), inplace=True)
df_billions_cleaned['longitude_country'].fillna(df_billions_cleaned['country'].map(long_dict), inplace=True)

# Printing the sum of null values to verify it doesn't have nulls

display(df_billions_cleaned[df_billions_cleaned['latitude_country'].isnull()].groupby('country').size().reset_index(name='no latitude figures').sort_values(by='no latitude figures', ascending=False))

display(df_billions_cleaned[df_billions_cleaned['longitude_country'].isnull()].groupby('country').size().reset_index(name='no longitude figures').sort_values(by='no longitude figures', ascending=False))

country  no latitude figures
0  Unknown                   38

country  no longitude figures
0  Unknown                    38

In [401]:
df_billions_cleaned.columns

Index(['rank', 'finalWorth', 'industry', 'personName', 'age', 'country',
       'city', 'source', 'to_be_deleted_1', 'countryOfCitizenship',
       'organization', 'selfMade', 'status', 'gender', 'birthDate', 'lastName',
       'firstName', 'title', 'date', 'state', 'residenceStateRegion',
       'birthYear', 'birthMonth', 'birthDay', 'cpi_country',
       'cpi_change_country', 'gdp_country',
       'gross_tertiary_education_enrollment',
       'gross_primary_education_enrollment_country', 'life_expectancy_country',
       'tax_revenue_country_country', 'total_tax_rate_country',
       'population_country', 'latitude_country', 'longitude_country',
       'continent'],
      dtype='object')

Addressing null values in `tax_revenue_country_country` and `total_tax_rate_country`

In [402]:
display(df_billions_cleaned[df_billions_cleaned['tax_revenue_country_country'].isnull()].groupby('continent').size().reset_index(name='no tax revenue data').sort_values(by='no tax revenue data', ascending=False))

display(df_billions_cleaned[df_billions_cleaned['total_tax_rate_country'].isnull()].groupby('continent').size().reset_index(name='no total tax rate').sort_values(by='no total tax rate', ascending=False))

continent  no tax revenue data
1           Asia                  111
4        Unknown                   38
2         Europe                   23
3  North America                    9
0         Africa                    1

continent  no total tax rate
1           Asia                111
4        Unknown                 38
2         Europe                 23
3  North America                  9
0         Africa                  1

In [403]:
# Creating variables to store median tax revenue in each continent

eu_tax_revenue = df_billions_cleaned[df_billions_cleaned['continent'] == 'Europe']['tax_revenue_country_country'].median()
na_tax_revenue = df_billions_cleaned[df_billions_cleaned['continent'] == 'North America']['tax_revenue_country_country'].median()
as_tax_revenue = df_billions_cleaned[df_billions_cleaned['continent'] == 'Asia']['tax_revenue_country_country'].median()
af_tax_revenue = df_billions_cleaned[df_billions_cleaned['continent'] == 'Africa']['tax_revenue_country_country'].median()

# Creating variables to store median total tax rate in each continent

eu_total_tax_rate = df_billions_cleaned[df_billions_cleaned['continent'] == 'Europe']['total_tax_rate_country'].median()
na_total_tax_rate = df_billions_cleaned[df_billions_cleaned['continent'] == 'North America']['total_tax_rate_country'].median()
as_total_tax_rate = df_billions_cleaned[df_billions_cleaned['continent'] == 'Asia']['total_tax_rate_country'].median()
af_total_tax_rate = df_billions_cleaned[df_billions_cleaned['continent'] == 'Africa']['total_tax_rate_country'].median()

display(eu_tax_revenue, na_tax_revenue, as_tax_revenue, af_tax_revenue)
display(eu_total_tax_rate, na_total_tax_rate, as_total_tax_rate, af_total_tax_rate)

# Create a dictionary to map continents to corresponding median values

continent_tax_revenue = {
    'Europe': eu_tax_revenue,
    'North America': na_tax_revenue,
    'Asia': as_tax_revenue,
    'Africa': af_tax_revenue
}

continent_total_tax_rate = {
    'Europe': eu_total_tax_rate,
    'North America': na_total_tax_rate,
    'Asia': as_total_tax_rate,
    'Africa': af_total_tax_rate
}

# Loop through continents and fill null values in the specified columns
for continent in ['Europe', 'North America', 'Asia', 'Africa']:
    df_billions_cleaned.loc[df_billions_cleaned['continent'] == continent, 'tax_revenue_country_country'] = df_billions_cleaned.loc[df_billions_cleaned['continent'] == continent, 'tax_revenue_country_country'].fillna(continent_tax_revenue[continent])
    df_billions_cleaned.loc[df_billions_cleaned['continent'] == continent, 'total_tax_rate_country'] = df_billions_cleaned.loc[df_billions_cleaned['continent'] == continent, 'total_tax_rate_country'].fillna(continent_total_tax_rate[continent])

# Printing the sum of null values to verify it doesn't have nulls

display(df_billions_cleaned[df_billions_cleaned['tax_revenue_country_country'].isnull()].groupby('continent').size().reset_index(name='no tax revenue data').sort_values(by='no tax revenue data', ascending=False))

display(df_billions_cleaned[df_billions_cleaned['total_tax_rate_country'].isnull()].groupby('continent').size().reset_index(name='no total tax rate').sort_values(by='no total tax rate', ascending=False))



14.2

9.6

9.4

17.2

46.2

36.6

59.2

39.3

continent  no tax revenue data
0   Unknown                   38

continent  no total tax rate
0   Unknown                 38

In [404]:
df_billions_cleaned['continent'].unique()

array(['Europe', 'North America', 'Asia', 'Oceania', 'South America',
       'Unknown', 'Africa'], dtype=object)

Addressing null values in `tax_revenue_country_country` and `total_tax_rate_country`

In [405]:
df_billions_cleaned.columns

Index(['rank', 'finalWorth', 'industry', 'personName', 'age', 'country',
       'city', 'source', 'to_be_deleted_1', 'countryOfCitizenship',
       'organization', 'selfMade', 'status', 'gender', 'birthDate', 'lastName',
       'firstName', 'title', 'date', 'state', 'residenceStateRegion',
       'birthYear', 'birthMonth', 'birthDay', 'cpi_country',
       'cpi_change_country', 'gdp_country',
       'gross_tertiary_education_enrollment',
       'gross_primary_education_enrollment_country', 'life_expectancy_country',
       'tax_revenue_country_country', 'total_tax_rate_country',
       'population_country', 'latitude_country', 'longitude_country',
       'continent'],
      dtype='object')

In [406]:


display(df_billions_cleaned[df_billions_cleaned['gross_tertiary_education_enrollment'].isnull()].groupby('continent').size().reset_index(name='no tertiary education data').sort_values(by='no tertiary education data', ascending=False))

display(df_billions_cleaned[df_billions_cleaned['gross_primary_education_enrollment_country'].isnull()].groupby('continent').size().reset_index(name='no primary education data').sort_values(by='no primary education data', ascending=False))

continent  no tertiary education data
1           Asia                         111
4        Unknown                          38
2         Europe                          22
3  North America                           9
0         Africa                           1

continent  no primary education data
1           Asia                        111
4        Unknown                         38
2         Europe                         22
3  North America                          9
0         Africa                          1

In [407]:
# Creating variables to store median tertiary education enrollment in each continent

eu_ter_edu = df_billions_cleaned[df_billions_cleaned['continent'] == 'Europe']['gross_tertiary_education_enrollment'].median()
na_ter_edu = df_billions_cleaned[df_billions_cleaned['continent'] == 'North America']['gross_tertiary_education_enrollment'].median()
as_ter_edu = df_billions_cleaned[df_billions_cleaned['continent'] == 'Asia']['gross_tertiary_education_enrollment'].median()
af_ter_edu = df_billions_cleaned[df_billions_cleaned['continent'] == 'Africa']['gross_tertiary_education_enrollment'].median()

# Creating variables to store median primary education enrollment in each continent

eu_pri_edu = df_billions_cleaned[df_billions_cleaned['continent'] == 'Europe']['gross_primary_education_enrollment_country'].median()
na_pri_edu = df_billions_cleaned[df_billions_cleaned['continent'] == 'North America']['gross_primary_education_enrollment_country'].median()
as_pri_edu = df_billions_cleaned[df_billions_cleaned['continent'] == 'Asia']['gross_primary_education_enrollment_country'].median()
af_pri_edu = df_billions_cleaned[df_billions_cleaned['continent'] == 'Africa']['gross_primary_education_enrollment_country'].median()

display(eu_ter_edu, na_ter_edu, as_ter_edu, af_ter_edu)
display(eu_pri_edu, na_pri_edu, as_pri_edu, af_pri_edu)

# Create a dictionary to map continents to corresponding median values

continent_ter_edu = {
    'Europe': eu_ter_edu,
    'North America': na_ter_edu,
    'Asia': as_ter_edu,
    'Africa': af_ter_edu
}

continent_pri_edu = {
    'Europe': eu_pri_edu,
    'North America': na_pri_edu,
    'Asia': as_pri_edu,
    'Africa': af_pri_edu
}

# Loop through continents and fill null values in the specified columns
for continent in ['Europe', 'North America', 'Asia', 'Africa']:
    df_billions_cleaned.loc[df_billions_cleaned['continent'] == continent, 'gross_tertiary_education_enrollment'] = df_billions_cleaned.loc[df_billions_cleaned['continent'] == continent, 'gross_tertiary_education_enrollment'].fillna(continent_ter_edu[continent])
    df_billions_cleaned.loc[df_billions_cleaned['continent'] == continent, 'gross_primary_education_enrollment_country'] = df_billions_cleaned.loc[df_billions_cleaned['continent'] == continent, 'gross_primary_education_enrollment_country'].fillna(continent_pri_edu[continent])

# Printing the sum of null values to verify it doesn't have nulls

display(df_billions_cleaned[df_billions_cleaned['gross_tertiary_education_enrollment'].isnull()].groupby('continent').size().reset_index(name='no tertiary education data').sort_values(by='no tertiary education data', ascending=False))

display(df_billions_cleaned[df_billions_cleaned['gross_primary_education_enrollment_country'].isnull()].groupby('continent').size().reset_index(name='no primary education data').sort_values(by='no primary education data', ascending=False))

67.0

88.2

50.6

22.4

102.6

101.8

100.2

100.9

continent  no tertiary education data
0   Unknown                          38

continent  no primary education data
0   Unknown                         38

Addressing null values in age-related columns: `birthDate`, `birthDay`, `birthMonth` `birthYear` and `age`

In [408]:
print(df_billions_cleaned[df_billions_cleaned['birthDate'].isnull()].groupby('country').size().reset_index(name='no birth date info').sort_values(by='no birth date info', ascending=False))

                 country  no birth date info
3                  China                  27
5                Germany                  14
15               Unknown                  12
6              Hong Kong                   3
10           Switzerland                   3
12              Thailand                   3
1                 Brazil                   2
2                 Canada                   2
11                Taiwan                   2
14        United Kingdom                   2
0              Argentina                   1
4                 France                   1
7                  Japan                   1
8              Singapore                   1
9                  Spain                   1
13  United Arab Emirates                   1


With ``age`` and age-related columns (`birthDay`, `birthMonth` `birthYear` and ``birthDate``) we have a curious case because unlike the economic and population columns, missing values belong to other countries. Also, the dataset has some values in the ``age`` column that are nulls in all the other age-related columns

In [409]:
# Check which columns have values in the birthDate column but not in the other age-related columns

df_billions_cleaned[(df_billions_cleaned['age'].notnull()) & (df_billions_cleaned['birthDay'].isna())]



rank  finalWorth         industry                         personName  \
423    418        6100       Technology                        Zhou Qunfei   
902    878        3300    Manufacturing                            Xue Hua   
904    905        3200  Food & Beverage  Karen Virginia Beckmann Legoretta   
913    905        3200       Automotive                       Dong Jinggui   
1494  1434        2100  Food & Beverage                           Shu Ping   
1592  1575        1900       Healthcare                           Dong Fan   
1759  1725        1700        Logistics                         Lai Jianfa   
1809  1804        1600    Manufacturing                         Bai Baokun   
2038  2020        1400  Food & Beverage                        Guan Yihong   
2069  2020        1400       Healthcare                         Liu Fangyi   
2437  2405        1100    Manufacturing                       Ruben Feffer   
2625  2540        1000       Automotive             Wang Jianfeng & family   

      age    country       city              source  to_be_deleted_1  \
423    53  Hong Kong  Hong Kong  Smartphone screens       Technology   
902    53      China  Guangzhou        Agribusiness    Manufacturing   
904    53    Unknown    Unknown             Tequila  Food & Beverage   
913    53      China       Wuxi   Electric scooters       Automotive   
1494   53  Singapore  Singapore         Restaurants  Food & Beverage   
1592   53      China     Zhuhai     Medical devices       Healthcare   
1759   53      China   Shanghai    Express delivery        Logistics   
1809   53      China   Dongguan            Hardware    Manufacturing   
2038   53      China  Guangzhou          Restaurant  Food & Beverage   
2069   53      China   Shanghai   Medical equipment       Healthcare   
2437   53     Brazil  São Paulo      Pulp and paper    Manufacturing   
2625   53      China     Ningbo          Auto parts       Automotive   

     countryOfCitizenship     organization  selfMade status gender birthDate  \
423             Hong Kong  Lens Technology      True      D      F       NaT   
902                 China          Unknown      True      D      M       NaT   
904                Mexico          Unknown     False      U      F       NaT   
913                 China          Unknown      True      U      M       NaT   
1494            Singapore          Unknown      True      U      F       NaT   
1592                China          Unknown      True      D      M       NaT   
1759                China          Unknown      True      U      M       NaT   
1809                China          Unknown      True      D      M       NaT   
2038                China          Unknown      True      U      M       NaT   
2069                China          Unknown      True      D      M       NaT   
2437               Brazil          Unknown     False      D      M       NaT   
2625                China          Unknown      True      D      M       NaT   

                lastName       firstName            title       date  \
423                 Zhou          Qunfei  Founder and CEO 2023-04-04   
902                  Xue             Hua          Unknown 2023-04-04   
904   Beckmann Legoretta  Karen Virginia          Unknown 2023-04-04   
913                 Dong         Jinggui          Unknown 2023-04-04   
1494                 Shu            Ping          Unknown 2023-04-04   
1592                Dong             Fan          Unknown 2023-04-04   
1759                 Lai          Jianfa          Unknown 2023-04-04   
1809                 Bai          Baokun          Unknown 2023-04-04   
2038                Guan          Yihong          Unknown 2023-04-04   
2069                 Liu          Fangyi          Unknown 2023-04-04   
2437              Feffer           Ruben          Unknown 2023-04-04   
2625                Wang        Jianfeng          Unknown 2023-04-04   

                     state  residenceStateRegion  birthYear  birthMonth  \
4

All the null values in the age-related columns that aren't null in the ``age`` column have a value in this last one of 53. It can be an astonishing coincidence, or just wrong data. In this case, all these values will be deleted as this scenario is highly improbable

In [410]:
# Deleting rows that contain suspicious data

df_billions_cleaned = df_billions_cleaned[~((df_billions_cleaned['age'].notnull()) & (df_billions_cleaned['birthDay'].isna()))]


In [411]:
# Defining a function to fill age-related columns with the most appropriate values

def age_related_stats(df, country):

    # Calculate mode for birthDay and birthMonth

    mode_day = df[df['country'] == country]['birthDay'].mode().values[0]
    mode_month = df[df['country'] == country]['birthMonth'].mode().values[0]

    # Calculate mean for birthYear
    
    mean_year = df[df['country'] == country]['birthYear'].mean()

    # Fill missing values

    condition = (df['country'] == country) & (df['birthDay'].isnull())
    df.loc[condition, 'birthDay'] = mode_day

    condition = (df['country'] == country) & (df['birthMonth'].isnull())
    df.loc[condition, 'birthMonth'] = mode_month

    condition = (df['country'] == country) & (df['birthYear'].isnull())
    df.loc[condition, 'birthYear'] = round(mean_year)

    return df





In [412]:
# Using the function to fill null values in age-related columns with calculated statistics

countries_to_fill = ['China', 'Germany', 'Switzerland', 'Thailand', 'Canada', 'Hong Kong', 'Taiwan', 'United Kingdom', 'Argentina', 'Brazil', 'France', 'Japan', 'Spain', 'United Arab Emirates']

for country in countries_to_fill:
    df_billions_cleaned = age_related_stats(df_billions_cleaned, country)

In [413]:
# Check rows that have filled values in age-related columns and lacks birthDate attribute

df_billions_cleaned[df_billions_cleaned['birthDay'].notnull() & (df_billions_cleaned['age'].isna())]

# Concatenate age-related columns attributes to build a synthetic date

df_billions_cleaned['birthDate'] = pd.to_datetime(df_billions_cleaned['birthYear'].astype(str) + '/' + df_billions_cleaned['birthMonth'].astype(str) + '/' + df_billions_cleaned['birthDay'].astype(str), errors='coerce')



In [414]:
df_billions_cleaned.isna().sum()

rank                                           0
finalWorth                                     0
industry                                       0
personName                                     0
age                                           65
country                                        0
city                                           0
source                                         0
to_be_deleted_1                                0
countryOfCitizenship                           0
organization                                   0
selfMade                                       0
status                                         0
gender                                         0
birthDate                                     11
lastName                                       0
firstName                                      0
title                                          0
date                                           0
state                                          0
residenceStateRegion

In [415]:
# Creating a function to calculate the age using the birthDate and the date columns for synthetic values

def calculate_age(row):
    if pd.notna(row['date']) and pd.notna(row['birthDate']):
        if pd.isna(row['age']):
            return int((row['date'] - row['birthDate']).days // 365)
        else:
            return row['age']


In [416]:
# Filling remaining nulls in the age column with the previous function

df_billions_cleaned['age'] = df_billions_cleaned.apply(calculate_age, axis=1)

In [417]:
# Creating the definitive dataset to be used in the analysis
columns_to_drop = ['to_be_deleted_1', 'selfMade', 'status', 'date']

df_ready = df_billions_cleaned[df_billions_cleaned['country'] != 'Unknown'].copy().drop(columns=columns_to_drop)
df_ready.shape


(2591, 32)

In [418]:
df_ready.columns

Index(['rank', 'finalWorth', 'industry', 'personName', 'age', 'country',
       'city', 'source', 'countryOfCitizenship', 'organization', 'gender',
       'birthDate', 'lastName', 'firstName', 'title', 'state',
       'residenceStateRegion', 'birthYear', 'birthMonth', 'birthDay',
       'cpi_country', 'cpi_change_country', 'gdp_country',
       'gross_tertiary_education_enrollment',
       'gross_primary_education_enrollment_country', 'life_expectancy_country',
       'tax_revenue_country_country', 'total_tax_rate_country',
       'population_country', 'latitude_country', 'longitude_country',
       'continent'],
      dtype='object')

In [419]:
df_ready.dtypes

rank                                                   int64
finalWorth                                             int64
industry                                              object
personName                                            object
age                                                  float64
country                                               object
city                                                  object
source                                                object
countryOfCitizenship                                  object
organization                                          object
gender                                                object
birthDate                                     datetime64[ns]
lastName                                              object
firstName                                             object
title                                                 object
state                                                 object
residenceStateRegion    

In [421]:
df_ready['age'] = df_ready['age'].astype('Int64')
df_ready.dtypes

rank                                                   int64
finalWorth                                             int64
industry                                              object
personName                                            object
age                                                    Int64
country                                               object
city                                                  object
source                                                object
countryOfCitizenship                                  object
organization                                          object
gender                                                object
birthDate                                     datetime64[ns]
lastName                                              object
firstName                                             object
title                                                 object
state                                                 object
residenceStateRegion    

In [425]:
new_column_names = ['position', 'wealth', 'category', 'full_name', 'age', 'country_of_residence', 'city_of_residence', 'source', 'citizenship', 'organization', 'gender', 'birth_date', 'last_name', 'first_name', 'title', 'residence_state', 'residence_region', 'birth_year', 'birth_month', 'birth_day', 'cpi_country', 'cpi_change_country', 'gdp_country', 'g_tertiary_ed_enroll', 'g_primary_ed_enroll', 'life_expectancy', 'tax_revenue', 'tax_rate', 'country_pop', 'country_lat', 'country_long', 'continent']

df_ready.columns = [new_column_names]
df_ready.head(4)

position  wealth          category                 full_name age  \
0        1  211000  Fashion & Retail  Bernard Arnault & family  74   
1        2  180000        Automotive                 Elon Musk  51   
2        3  114000        Technology                Jeff Bezos  59   
3        4  107000        Technology             Larry Ellison  78   

  country_of_residence city_of_residence         source    citizenship  \
0               France             Paris           LVMH         France   
1        United States            Austin  Tesla, SpaceX  United States   
2        United States            Medina         Amazon  United States   
3        United States             Lanai         Oracle  United States   

                       organization gender birth_date last_name first_name  \
0  LVMH Moët Hennessy Louis Vuitton      M 1949-03-05   Arnault    Bernard   
1                             Tesla      M 1971-06-28      Musk       Elon   
2                            Amazon      M 1964-01-12     Bezos       Jeff   
3                            Oracle      M 1944-08-17   Ellison      Larry   

                  title       residence_state      residence_region  \
0      Chairman and CEO  No subdivisions info  No subdivisions info   
1                   CEO                 Texas                 South   
2  Chairman and Founder            Washington                  West   
3       CTO and Founder                Hawaii                  West   

  birth_year birth_month birth_day cpi_country cpi_change_country  \
0       1949           3         5      110.05                1.1   
1       1971           6        28      117.24                7.5   
2       1964           1        12      117.24                7.5   
3       1944           8        17      117.24                7.5   

      gdp_country g_tertiary_ed_enroll g_primary_ed_enroll life_expectancy  \
0   2715518274227                 65.6               102.5            82.5   
1  21427700000000                 88.2               101.8            78.5   
2  21427700000000                 88.2               101.8            78.5   
3  21427700000000                 88.2               101.8            78.5   

  tax_revenue tax_rate country_pop country_lat country_long      continent  
0        24.2     60.7    67059887   46.227638     2.213749         Europe  
1         9.6     36.6   328239523   37.090240   -95.712891  North America  
2         9.6     36.6   328239523   37.090240   -95.712891  North America  
3         9.6     36.6   328239523   37.090240   -95.712891  North America

In [426]:
# Converting the dataset to a .csv file to use it for analysis

df_ready.to_csv('df_ready.csv', index=False)
